In [6]:
import numpy as np

In [9]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
a = [1,2,3,"hello"]
a  

[1, 2, 3, 'hello']

In [15]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [16]:
a

[1, 2, 3, 'hello']

In [17]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
l
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation Function

In [21]:
arp = np.arange(1,11,2)

In [22]:
arp

array([1, 3, 5, 7, 9])

In [25]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [26]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
arr = np.ones(2)

In [28]:
arr

array([1., 1.])

In [33]:
arr = np.linspace(1,5,10)

In [34]:
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Generation Function

In [36]:
np.random.rand(10)

array([0.87766998, 0.98917438, 0.87748376, 0.31965295, 0.89703322,
       0.62005211, 0.03391704, 0.16304561, 0.21342148, 0.56849748])

In [37]:
np.random.randn(10)

array([-1.99849116,  0.60002274,  1.17041808,  0.16292284,  2.17408686,
       -0.97031397, -0.36792777,  0.90618697,  0.74385328, -2.30771834])

In [45]:
np.random.randint(6,30,4)

array([10, 17, 27, 12], dtype=int32)

In [47]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr.shape

(3, 3)

In [51]:
arr.size

9

Array Methods

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [55]:
arr.sum()


np.int64(45)

In [56]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [57]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [58]:
arr.mean()

np.float64(5.0)

In [59]:
arr.std()

np.float64(2.581988897471611)

In [60]:
arr.argmax()

np.int64(8)

In [61]:
arr.argmin()

np.int64(0)

In [62]:
arr = np.arange(1,31)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr =arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Array indexing and operations

Numpy INDEXING AND SLICING OF VECTORS

In [66]:
arr = np.arange(11,21) 

In [67]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
arr[9]

np.int64(20)

In [70]:
arr[1:5:2]

array([12, 14])

NUMPY INDEXING AND SLICING OF MATRIX

In [71]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [73]:
arr[0,0]

np.int64(1)

In [76]:
slic = arr[0:2,1:3]

In [77]:
slic

array([[2, 3],
       [7, 8]])

In [81]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [82]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Booolean Indeixing


In [88]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [91]:
arr = arr[bool_index]

In [92]:
arr

array([12, 14, 16, 18, 20])

ARRAY OPERATIONS

Arithmetic operations

In [93]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [94]:
arr1 = a1+a2

array([ 7,  9, 11, 13, 15])

In [95]:
arr2 = a1-a2

In [96]:
arr2

array([-5, -5, -5, -5, -5])

In [97]:
arr3 = a1/a2
arr3

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Broadcasting

In [98]:
l = [10,20,30,40,50]
arr = np.array(l)

In [99]:
arr + 10

array([20, 30, 40, 50, 60])